export const DEFAULT_API_PORT = 3001;
export const DEFAULT_API_HOST = "0.0.0.0";
export const DEFAULT_BODY_LIMIT_BYTES = 262144;
export const INQUIRY_BODY_LIMIT_BYTES = 32 * 1024;
export const DEFAULT_INQUIRY_RATE_LIMIT_MAX = 5;
export const DEFAULT_INQUIRY_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const DEFAULT_INQUIRY_FETCH_TIMEOUT_MS = 15_000;
export const DEFAULT_MANAGEMENT_FETCH_TIMEOUT_MS = 15_000;
export const MAX_BEARER_TOKEN_LENGTH = 8192;
export const MANAGEMENT_INQUIRY_LIST_DEFAULT_LIMIT = 20;
export const MANAGEMENT_INQUIRY_LIST_MIN_LIMIT = 1;
export const MANAGEMENT_INQUIRY_LIST_MAX_LIMIT = 50;
export const MANAGEMENT_INQUIRY_CURSOR_MAX_LENGTH = 256;

export const SUPPORTED_ASYMMETRIC_JWT_ALGORITHMS = [
  "ES256",
  "ES384",
  "ES512",
  "RS256",
  "RS384",
  "RS512",
  "PS256",
  "PS384",
  "PS512",
  "EdDSA",
] as const;

export type SupportedAsymmetricJwtAlgorithm = (typeof SUPPORTED_ASYMMETRIC_JWT_ALGORITHMS)[number];

export const SERVER_ENV_KEYS = [
  "NODE_ENV",
  "HOST",
  "PORT",
  "CORS_ORIGINS",
  "DATABASE_URL",
  "INQUIRY_RATE_LIMIT_MAX",
  "INQUIRY_RATE_LIMIT_WINDOW",
  "TRUST_RENDER_CLIENT_IP",
  "MANAGEMENT_AUTH_ENABLED",
  "NEON_AUTH_JWKS_URL",
  "NEON_AUTH_ISSUER",
  "NEON_AUTH_AUDIENCE",
  "NEON_AUTH_JWT_ALGORITHMS",
  "WALTER_ADMIN_USER_IDS",
  "R2_ACCOUNT_ID",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "R2_BUCKET",
  "R2_PUBLIC_BASE_URL",
  "RESEND_API_KEY",
  "INQUIRY_NOTIFICATION_TO",
  "STATIC_SITE_DEPLOY_HOOK_URL",
] as const;

export const PUBLIC_ENV_KEYS = [
  "NEXT_PUBLIC_API_BASE_URL",
  "NEXT_PUBLIC_NEON_AUTH_BASE_URL",
] as const;
