export const MANAGEMENT_COPY = {
  heading: "Management sign in",
  supporting: "This area is for authorised administrators only.",
  emailLabel: "Email",
  passwordLabel: "Password",
  submitLabel: "Sign in",
  submittingLabel: "Signing in…",
  restoring: "Checking your session…",
  unavailable: "Management sign-in is not available yet.",
  invalid: "Check your email and password.",
  forbidden: "This account is not authorised for management.",
  sessionUnavailable: "Management session verification is not available yet.",
  timeout: "The management request timed out. Try again.",
  unexpected: "The management request could not be completed.",
  malformed: "The management response was not valid.",
  signedIn: "Signed in as administrator.",
  signOut: "Sign out",
  signingOutLabel: "Signing out…",
  signedOut: "You are signed out.",
  signOutTimeout:
    "Local management data was cleared, but the identity provider timed out. Close this browser and try signing out again.",
  signOutProviderError:
    "Local management data was cleared, but the identity provider could not complete sign-out. Close this browser and try again.",
  sessionExpired: "Your session expired. Sign in again.",
  skipToContent: "Skip to management content",
  sectionNavLabel: "Management sections",
  inquiriesSection: "Inquiries",
  contentSection: "Website Content",
  publicationSection: "Publication",
  inboxHeading: "Inquiries",
  filterGroupLabel: "Inquiry status filters",
  filterAll: "All",
  filterNew: "New",
  filterInProgress: "In progress",
  filterClosed: "Closed",
  emptyInbox: "No inquiries match this filter.",
  inboxUnavailable: "Inquiry records are not available yet.",
  loadMore: "Load more inquiries",
  loadingMore: "Loading more…",
  hasAttachment: "Has attachment metadata",
  noAttachmentShort: "No attachment metadata",
  backToInbox: "Back to inbox",
  statusLabel: "Status",
  updateStatus: "Update status",
  updatingStatus: "Updating…",
  detailHeading: "Inquiry",
  receivedLabel: "Received",
  updatedLabel: "Updated",
  attachmentLabel: "Attachment metadata",
  noAttachment: "No attachment metadata",
  contentHeading: "Website Content",
  contentSupporting: "Edit approved public copy locally. Saving a draft does not change the public static website.",
  contentUnavailable: "Website content drafts are not available yet.",
  saveDraft: "Save draft",
  savingDraft: "Saving…",
  resetDraft: "Reset to canonical",
  draftSaved: "Saved draft",
  draftCanonical: "Canonical copy",
  unsaved: "Unsaved changes",
  canonicalValueLabel: "Canonical value",
  draftValueLabel: "Draft value",
  previewHeading: "Local preview",
  previewNotice: "This preview is local only. It does not publish copy or regenerate the public static export.",
  contentConflict:
    "This draft was updated elsewhere. Your unsaved text is still here. Reload the server draft to continue.",
  reloadServerDraft: "Reload Server Draft",
  draftSavedPublicUnchanged: "Draft saved. The public website has not changed.",
  draftResetPublicUnchanged: "Draft reset to canonical copy. The public website has not changed.",
  tooShort: "This field is too short.",
  tooLong: "This field is too long.",
  htmlNotAllowed: "HTML is not allowed. Use plain text.",
  publicationHeading: "Prepared publications",
  publicationSupporting:
    "Prepare an immutable local publication of approved copy overlays. This does not rebuild the public static website or call a Render deploy hook.",
  publicationUnavailable: "Publications are not available yet.",
  preparePublication: "Prepare publication",
  preparingPublication: "Preparing publication…",
  emptyPublications: "No prepared publications yet.",
  publicationPreviewHeading: "Prepared overlay preview",
  publicationEntryCount: "Entries",
  publicationStatus: "prepared",
  loadMorePublications: "Load more publications",
  loadingMorePublications: "Loading more publications…",
} as const;
